USE task_db; 

CREATE TABLE m_category( 
    category_id INT AUTO_INCREMENT PRIMARY KEY
    , category_name VARCHAR (20) UNIQUE NOT NULL
    , update_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO 
